"use client";

import { useRef,useState,useTransition } from "react";
import { testSmtpConnection,updateCompanySettings } from "./actions";

type Settings={businessName:string;taxId:string;address:string;postalCode:string;city:string;province:string;phone:string;email:string;website:string;quotePrefix:string;defaultValidityDays:number;logoUrl:string|null};
type EmailSettings={tableReady:boolean;enabled:boolean;host:string;port:number;secure:boolean;user:string;fromAddress:string;passwordConfigured:boolean};
const input="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10 dark:border-slate-700 dark:bg-slate-950";

export function CompanySettingsForm({settings,emailSettings}:{settings:Settings;emailSettings:EmailSettings}){
 const formRef=useRef<HTMLFormElement>(null);const [pending,startTransition]=useTransition();const [message,setMessage]=useState<{ok:boolean;text:string}|null>(null);
 function testEmail(){const form=formRef.current;if(!form)return;setMessage(null);const data=new FormData(form);startTransition(async()=>{const saved=await updateCompanySettings(data);if(!saved.ok){setMessage({ok:false,text:saved.error||"No se ha podido guardar."});return;}const result=await testSmtpConnection();setMessage({ok:result.ok,text:result.ok?"Configuración guardada y conexión con Gmail correcta.":result.error||"No se ha podido comprobar."});});}
 return <form ref={formRef} onSubmit={e=>{e.preventDefault();setMessage(null);const data=new FormData(e.currentTarget);startTransition(async()=>{const result=await updateCompanySettings(data);setMessage({ok:result.ok,text:result.ok?"Configuración guardada correctamente.":result.error||"No se ha podido guardar."});});}} className="space-y-6">
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-6"><h2 className="text-lg font-semibold">Identidad de la empresa</h2><p className="mb-5 text-sm text-slate-500">Estos datos aparecerán en la cabecera de cada PDF.</p><div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre o razón social" name="businessName" value={settings.businessName} required/><Field label="CIF / NIF" name="taxId" value={settings.taxId}/><div className="sm:col-span-2"><Field label="Dirección" name="address" value={settings.address}/></div><Field label="Código postal" name="postalCode" value={settings.postalCode}/><Field label="Localidad" name="city" value={settings.city}/><Field label="Provincia" name="province" value={settings.province}/><Field label="Teléfono" name="phone" value={settings.phone}/><Field label="Email" name="email" value={settings.email} type="email"/><Field label="Web" name="website" value={settings.website}/></div><div className="mt-5"><label className="mb-1.5 block text-sm font-medium">Logo</label><input name="logo" type="file" accept="image/*" className={`${input} file:mr-3 file:rounded-lg file:border-0 file:bg-blue-50 file:px-3 file:py-2 file:text-sm file:font-semibold file:text-blue-700`}/>{settings.logoUrl?<p className="mt-2 text-xs text-emerald-600">Hay un logo guardado. Selecciona otro archivo solamente para sustituirlo.</p>:<p className="mt-2 text-xs text-slate-500">PNG o JPG, hasta 5 MB.</p>}</div></section>
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-6"><h2 className="text-lg font-semibold">Preferencias de presupuestos</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Prefijo de numeración" name="quotePrefix" value={settings.quotePrefix} required/><Field label="Validez predeterminada (días)" name="defaultValidityDays" value={String(settings.defaultValidityDays)} type="number" required/></div><p className="mt-3 text-xs text-slate-500">Los precios se consideran finales con IVA del 21% incluido.</p></section>
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Envío por correo</h2><p className="text-sm text-slate-500">Los presupuestos se enviarán utilizando esta cuenta SMTP.</p></div>{emailSettings.tableReady?<label className="flex items-center gap-2 text-sm font-medium"><input name="smtpEnabled" type="checkbox" defaultChecked={emailSettings.enabled} className="h-4 w-4 rounded border-slate-300"/>Activar email</label>:null}</div><input type="hidden" name="smtpTableReady" value={String(emailSettings.tableReady)}/>{emailSettings.tableReady?<><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Servidor SMTP" name="smtpHost" value={emailSettings.host} placeholder="smtp.gmail.com"/><Field label="Puerto" name="smtpPort" value={String(emailSettings.port)} type="number"/><Field label="Usuario" name="smtpUser" value={emailSettings.user} placeholder="correo@empresa.com"/><Field label="Remitente" name="smtpFrom" value={emailSettings.fromAddress} placeholder="Empresa <correo@empresa.com>"/><div className="sm:col-span-2"><label className="mb-1.5 block text-sm font-medium">Contraseña SMTP</label><input name="smtpPassword" type="password" autoComplete="new-password" className={input} placeholder={emailSettings.passwordConfigured?"Guardada · déjalo vacío para conservarla":"Contraseña o contraseña de aplicación"}/><p className="mt-1.5 text-xs text-slate-500">Se guarda cifrada y nunca vuelve a mostrarse. En Gmail debes usar una contraseña de aplicación.</p></div><label className="flex items-center gap-2 text-sm"><input name="smtpSecure" type="checkbox" defaultChecked={emailSettings.secure} className="h-4 w-4 rounded border-slate-300"/>Conexión SSL/TLS directa (normalmente puerto 465)</label></div><button type="button" onClick={testEmail} disabled={pending} className="mt-5 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold transition hover:bg-slate-50 disabled:opacity-60 dark:border-slate-700 dark:hover:bg-slate-800">{pending?"Guardando y comprobando…":"Guardar y probar conexión"}</button></>:<div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">La configuración estará disponible después de ejecutar una única consulta en Supabase.</div>}</section>
  {message?<div className={`rounded-xl border p-4 text-sm ${message.ok?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-red-200 bg-red-50 text-red-700"}`}>{message.text}</div>:null}<button disabled={pending} className="rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 px-6 py-3 text-sm font-semibold text-white shadow-lg shadow-blue-500/20 disabled:opacity-60">{pending?"Guardando…":"Guardar configuración"}</button>
 </form>;
}

function Field({label,name,value,type="text",required=false,placeholder}:{label:string;name:string;value:string;type?:string;required?:boolean;placeholder?:string}){return <div><label className="mb-1.5 block text-sm font-medium">{label}</label><input name={name} defaultValue={value} type={type} required={required} placeholder={placeholder} className={input}/></div>}
