"use client";

import { useState,useTransition } from "react";
import { updateCompanySettings } from "./actions";

type Settings={businessName:string;taxId:string;address:string;postalCode:string;city:string;province:string;phone:string;email:string;website:string;quotePrefix:string;defaultValidityDays:number;logoUrl:string|null};
const input="w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10 dark:border-slate-700 dark:bg-slate-950";

export function CompanySettingsForm({settings}:{settings:Settings}){
 const [pending,startTransition]=useTransition();const [message,setMessage]=useState<{ok:boolean;text:string}|null>(null);
 return <form onSubmit={e=>{e.preventDefault();setMessage(null);const data=new FormData(e.currentTarget);startTransition(async()=>{const result=await updateCompanySettings(data);setMessage({ok:result.ok,text:result.ok?"Configuración guardada correctamente.":result.error||"No se ha podido guardar."});});}} className="space-y-6">
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-6"><h2 className="text-lg font-semibold">Identidad de la empresa</h2><p className="mb-5 text-sm text-slate-500">Estos datos aparecerán en la cabecera de cada PDF.</p><div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre o razón social" name="businessName" value={settings.businessName} required input={input}/><Field label="CIF / NIF" name="taxId" value={settings.taxId} input={input}/><div className="sm:col-span-2"><Field label="Dirección" name="address" value={settings.address} input={input}/></div><Field label="Código postal" name="postalCode" value={settings.postalCode} input={input}/><Field label="Localidad" name="city" value={settings.city} input={input}/><Field label="Provincia" name="province" value={settings.province} input={input}/><Field label="Teléfono" name="phone" value={settings.phone} input={input}/><Field label="Email" name="email" value={settings.email} type="email" input={input}/><Field label="Web" name="website" value={settings.website} input={input}/></div><div className="mt-5"><label className="mb-1.5 block text-sm font-medium">Logo</label><input name="logo" type="file" accept="image/*" className={`${input} file:mr-3 file:rounded-lg file:border-0 file:bg-blue-50 file:px-3 file:py-2 file:text-sm file:font-semibold file:text-blue-700`}/>{settings.logoUrl?<p className="mt-2 text-xs text-emerald-600">Hay un logo guardado. Selecciona otro archivo solamente para sustituirlo.</p>:<p className="mt-2 text-xs text-slate-500">PNG o JPG, hasta 5 MB.</p>}</div></section>
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-6"><h2 className="text-lg font-semibold">Preferencias de presupuestos</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Prefijo de numeración" name="quotePrefix" value={settings.quotePrefix} required input={input}/><Field label="Validez predeterminada (días)" name="defaultValidityDays" value={String(settings.defaultValidityDays)} type="number" required input={input}/></div><p className="mt-3 text-xs text-slate-500">Los precios se consideran finales con IVA del 21% incluido.</p></section>
  {message?<div className={`rounded-xl border p-4 text-sm ${message.ok?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-red-200 bg-red-50 text-red-700"}`}>{message.text}</div>:null}<button disabled={pending} className="rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 px-6 py-3 text-sm font-semibold text-white shadow-lg shadow-blue-500/20 disabled:opacity-60">{pending?"Guardando…":"Guardar configuración"}</button>
 </form>;
}

function Field({label,name,value,input,type="text",required=false}:{label:string;name:string;value:string;input:string;type?:string;required?:boolean}){return <div><label className="mb-1.5 block text-sm font-medium">{label}</label><input name={name} defaultValue={value} type={type} required={required} className={input}/></div>}
