import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { formatMoney } from "@/lib/quote-calculations";

export const dynamic = "force-dynamic";
const labels: Record<string,string> = { DRAFT:"Borrador", SENT:"Enviado", ACCEPTED:"Aceptado", REJECTED:"Rechazado", EXPIRED:"Caducado" };
const styles: Record<string,string> = { DRAFT:"bg-slate-100 text-slate-700", SENT:"bg-blue-100 text-blue-700", ACCEPTED:"bg-emerald-100 text-emerald-700", REJECTED:"bg-red-100 text-red-700", EXPIRED:"bg-amber-100 text-amber-700" };

export default async function QuotesPage() {
  const quotes = await prisma.quote.findMany({ include: { _count: { select: { items: true } } }, orderBy: { createdAt: "desc" } });
  const accepted = quotes.filter(q=>q.status==="ACCEPTED").reduce((s,q)=>s+q.totalCents,0);
  return <div className="space-y-7">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-blue-600 dark:text-cyan-300">Gestión comercial</p><h1 className="text-3xl font-bold tracking-tight">Presupuestos</h1><p className="mt-1 text-sm text-slate-500">Consulta todos los presupuestos y su estado.</p></div><Link href="/catalogo/presupuestos/nuevo" className="inline-flex items-center justify-center rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-blue-500/20">+ Nuevo presupuesto</Link></div>
    <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Total creados</p><p className="mt-2 text-3xl font-bold">{quotes.length}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Pendientes</p><p className="mt-2 text-3xl font-bold text-blue-600">{quotes.filter(q=>["DRAFT","SENT"].includes(q.status)).length}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Aceptados</p><p className="mt-2 text-3xl font-bold text-emerald-600">{formatMoney(accepted)}</p></div></div>
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">{quotes.length===0?<div className="p-12 text-center"><p className="font-medium">Todavía no hay presupuestos</p><p className="mt-1 text-sm text-slate-500">Crea el primero seleccionando piezas del catálogo.</p></div>:<div className="divide-y divide-slate-100 dark:divide-slate-800">{quotes.map(q=><Link key={q.id} href={`/catalogo/presupuestos/${q.id}`} className="grid gap-3 px-5 py-4 transition hover:bg-slate-50 dark:hover:bg-slate-800/50 sm:grid-cols-[150px_1fr_130px_130px] sm:items-center"><div><p className="font-mono text-sm font-semibold text-blue-700 dark:text-cyan-300">{q.number}</p><p className="text-xs text-slate-400">{new Intl.DateTimeFormat("es-ES").format(q.createdAt)}</p></div><div><p className="font-medium">{q.customerName}</p><p className="text-xs text-slate-500">{q.customerPhone} · {q._count.items} líneas</p></div><div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${styles[q.status]||styles.DRAFT}`}>{labels[q.status]||q.status}</span></div><p className="text-right text-lg font-bold">{formatMoney(q.totalCents)}</p></Link>)}</div>}</div>
  </div>;
}
