import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { formatMoney } from "@/lib/quote-calculations";
import { QuoteActions } from "./QuoteActions";

export const dynamic="force-dynamic";
const labels:Record<string,string>={DRAFT:"Borrador",SENT:"Enviado",ACCEPTED:"Aceptado",REJECTED:"Rechazado",EXPIRED:"Caducado"};

export default async function QuoteDetailPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params; const quote=await prisma.quote.findUnique({where:{id},include:{items:{orderBy:{position:"asc"}},deliveries:{orderBy:{createdAt:"desc"}}}}); if(!quote)notFound();
 return <div className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><Link href="/catalogo/presupuestos" className="text-sm font-medium text-blue-600">← Presupuestos</Link><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="font-mono text-3xl font-bold tracking-tight">{quote.number}</h1><span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-semibold text-blue-700">{labels[quote.status]||quote.status}</span></div><p className="mt-1 text-sm text-slate-500">Creado el {new Intl.DateTimeFormat("es-ES",{dateStyle:"long"}).format(quote.issueDate)}</p></div><p className="text-3xl font-bold text-slate-950 dark:text-white">{formatMoney(quote.totalCents)}</p></div>
 <div className="grid gap-6 xl:grid-cols-[1fr_380px]"><div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-xs font-semibold uppercase tracking-wide text-blue-600">Cliente</p><h2 className="mt-2 text-xl font-bold">{quote.customerName}</h2><div className="mt-2 flex flex-wrap gap-4 text-sm text-slate-500"><span>{quote.customerPhone}</span>{quote.customerEmail?<span>{quote.customerEmail}</span>:null}</div></section><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="border-b border-slate-100 px-5 py-4 dark:border-slate-800"><h2 className="font-semibold">Piezas</h2></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{quote.items.map(item=><div key={item.id} className="grid gap-2 px-5 py-4 sm:grid-cols-[1fr_70px_120px_120px]"><div><p className="font-medium">{item.description}</p>{item.discountBps?<p className="text-xs text-emerald-600">Descuento: {item.discountBps/100}%</p>:null}</div><p className="text-sm text-slate-500">× {item.quantity}</p><p className="text-sm text-slate-500">{formatMoney(item.unitPriceCents)}</p><p className="text-right font-semibold">{formatMoney(item.totalCents)}</p></div>)}</div></section>{quote.notes?<section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold">Notas y condiciones</h2><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600 dark:text-slate-300">{quote.notes}</p></section>:null}</div>
 <aside className="space-y-5"><section className="rounded-2xl bg-slate-950 p-6 text-white"><div className="space-y-3 text-sm"><div className="flex justify-between text-slate-400"><span>Base imponible</span><span>{formatMoney(quote.taxBaseCents)}</span></div><div className="flex justify-between text-slate-400"><span>IVA incluido ({quote.taxRateBps/100}%)</span><span>{formatMoney(quote.taxCents)}</span></div><div className="flex justify-between border-t border-white/10 pt-4 text-lg font-bold"><span>Total</span><span className="text-cyan-300">{formatMoney(quote.totalCents)}</span></div></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="mb-4 font-semibold">Enviar y gestionar</h2><QuoteActions id={id} number={quote.number} phone={quote.customerPhone} email={quote.customerEmail} status={quote.status}/></section><section className="rounded-2xl border border-slate-200 bg-white p-5 text-sm shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold">Historial de envío</h2>{quote.deliveries.length?<div className="mt-3 space-y-3">{quote.deliveries.map(d=><div key={d.id} className="flex justify-between gap-3"><span>{d.channel} · {d.status}</span><time className="text-xs text-slate-400">{new Intl.DateTimeFormat("es-ES",{dateStyle:"short",timeStyle:"short"}).format(d.createdAt)}</time></div>)}</div>:<p className="mt-2 text-slate-500">Todavía no se ha enviado.</p>}</section></aside></div></div>;
}
