"use client";

import { useState, useTransition } from "react";
import { recordWhatsAppShare, updateQuoteStatus } from "../actions";
import { sendQuoteEmail } from "./delivery-actions";

export function QuoteActions({ id, number, phone, email, status }: {id:string;number:string;phone:string;email:string|null;status:string}) {
  const [message,setMessage]=useState<string|null>(null); const [pending,startTransition]=useTransition();
  function shareWhatsApp(){ startTransition(async()=>{ setMessage(null); try { const response=await fetch(`/api/presupuestos/${id}/pdf`); const blob=await response.blob(); const file=new File([blob],`${number}.pdf`,{type:"application/pdf"}); if(navigator.share && (!navigator.canShare || navigator.canShare({files:[file]}))){ await navigator.share({title:`Presupuesto ${number}`,text:`Te envío el presupuesto ${number}.`,files:[file]}); } else { const url=URL.createObjectURL(blob); const link=document.createElement("a"); link.href=url; link.download=`${number}.pdf`; link.click(); URL.revokeObjectURL(url); const clean=phone.replace(/\D/g,""); const international=clean.length===9?`34${clean}`:clean; window.open(`https://wa.me/${international}?text=${encodeURIComponent(`Hola, te envío el presupuesto ${number}. El PDF se ha descargado para adjuntarlo.`)}`,"_blank","noopener,noreferrer"); } await recordWhatsAppShare(id); setMessage("PDF preparado para compartir por WhatsApp."); } catch(e){ if((e as Error).name!=="AbortError")setMessage("No se ha podido preparar el PDF."); } }); }
  function emailQuote(){ startTransition(async()=>{setMessage(null);const result=await sendQuoteEmail(id);setMessage(result.ok?"Presupuesto enviado por email.":result.error||"No se ha podido enviar.");});}
  return <div className="space-y-3"><div className="grid gap-2 sm:grid-cols-2"><a href={`/api/presupuestos/${id}/pdf`} target="_blank" className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-center text-sm font-semibold text-slate-700 shadow-sm hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200">Ver / descargar PDF</a><button onClick={shareWhatsApp} disabled={pending} className="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-semibold text-white hover:bg-emerald-700 disabled:opacity-60">Compartir por WhatsApp</button><button onClick={emailQuote} disabled={pending||!email} className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white hover:bg-blue-700 disabled:opacity-50">Enviar por email</button><select value={status} onChange={e=>startTransition(()=>updateQuoteStatus(id,e.target.value))} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-medium dark:border-slate-700 dark:bg-slate-900"><option value="DRAFT">Borrador</option><option value="SENT">Enviado</option><option value="ACCEPTED">Aceptado</option><option value="REJECTED">Rechazado</option><option value="EXPIRED">Caducado</option></select></div>{!email?<p className="text-xs text-amber-600">Añade un email al cliente para poder enviarlo automáticamente.</p>:null}{message?<p className="rounded-lg bg-slate-100 px-3 py-2 text-sm dark:bg-slate-800">{message}</p>:null}</div>;
}
